export const SAVE_LOCATION = "SAVE_LOCATION";
export const CHANGE_VALUE = "CHANGE_VALUE";
export const PLAY_TIMER = "PLAY_TIMER";
export const STOP_TIMER = "STOP_TIMER";
export const REFRESH_TIMER = "REFRESH_TIMER";
export const ADD_GUESSED_NUMBER = "ADD_GUESSED_NUMBER";
export const ADD_RANDOM_NUMBER = "ADD_RANDOM_NUMBER";
